name: Publish StackOverflow Articles
on: [push]
jobs:
  Publish_Article:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip3 install requests
      - run: python3 to_stackoverflow.py
        env:
          key: ${{ secrets.key }} 
      - run: echo "🔎 Pushed from ${{ github.ref }} to ${{ github.repository }} and updated StackOverflow articles accordingly."